export const HomeActionType = {
  GET_HOME_START: "GET_HOME_START",
  GET_HOME_SUCCESS: "GET_HOME_SUCCESS",
  GET_HOME_FAIL: "GET_HOME_FAIL",

  DELETE_HOME_START: "DELETE_HOME_START",
  DELETE_HOME_SUCCESS: "DELETE_HOME_SUCCESS",
  DELETE_HOME_FAIL: "DELETE_HOME_FAIL",
};
