const PostData = [
  {
    albumId: 1,
    id: 1,
    title: "aqsa-choudhary",
    img: "c.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see anomalyhaircare in @target for the first time…so surreal!! 🎨♥️😍",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 2,
    title: "aqsa-choudhary",
    img: "fairy.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 3,
    title: "sonobia-choudhary",
    img: "b.jpg",
    Likes: "100,likes",
    discription:
      "firuz.shoes_ *BIRTHDAY WEEK IS HERE!*FLAT OFF ON ALL PRODUCTS!Visit www.firuz.pk to avail amazing discounts",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 4,
    title: "aliyana ",
    img: "c.jpg",
    Likes: "100,likes",
    discription:
      "google Alert, alert: Godzilla and Kong are on the loose… in your living room! Unleash these iconic characters using AR on your... ",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 5,
    title: "iqra-choudhary",
    img: "nature.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 6,
    title: "sidra-choudhary",
    img: "painting.jpg",
    Likes: "100,likes",
    discription:
      "Apple Green: Lawn-Cotton Sequins Embroidered Kameez and CulottesLilac: Lawn-Cotton Sequins Embroidered Kameez and Sharara Pants",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 7,
    title: "Ayat Ali",
    img: "peace.jpg",
    Likes: "100,likes",
    discription: "ethnic_oftr Sanchi // Rozana Eid Collection",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 8,
    title: "sehrish muneeer",
    img: "fairy.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍❤️❤️",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 9,
    title: "tahreem fatima",
    img: "cl.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 10,
    title: "messi",
    img: "bl.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 11,
    title: "ronaldo",
    img: "nature.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 12,
    title: "leona",
    img: "painting.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
  {
    albumId: 1,
    id: 13,
    title: "marry levana",
    img: "peace.jpg",
    Likes: "100,likes",
    discription:
      "priyankachopra Finally made my way back to the states to see @anomalyhaircare in @target for the first time…so surreal!! 😍",
    option: "post",
    comment: "kk",
    share: "(53)",
  },
];
export default PostData;
